ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    predict_to_current_time: false   
    
    odom0: /odom/sample
    odom0_config: [true, true, false,
                       false, false, true,
                       false, false, false,
                       false, false, true,
                       false, false, false]
    odom0_queue_size: 10
